version: "3.9"
services:
    database_postgres:
        container_name: database_postgres
        image: postgres:12-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: db_myonewallet
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    app:
        container_name: app
        build: .
        links:
            - database_postgres
        command: sh -c "yarn test"
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
            DATABASE_HOST: database_postgres
            DATABASE_PORT: 5432
