version: "3.9"
services:
    postgres:
        image: postgres:13-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: myopenmarket
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./scripts/postgres:/docker-entrypoint-initdb.d

    migration:
        build: .
        command: sh -c "yarn db:migrate-deploy"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/myopenmarket?schema=myopenmarket

    tests:
        build: .
        depends_on:
            - migration
            - postgres
        command: sh -c "yarn dev"
        environment:
            PORT: 8080
            DATABASE_HOST: database_postgres
            DATABASE_PORT: 5432