version: "3.9"
services:
    postgres:
        image: postgres:13-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: myopenmarket
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./compose/postgres:/docker-entrypoint-initdb.d

    migration:
        build: .
        command: sh -c "yarn db:migrate-deploy"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/myopenmarket?pool_timeout=80&connect_timeout=80

    tests:
        build: .
        command: sh -c "yarn db:migrate-deploy && yarn test"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/myopenmarket?pool_timeout=80&connect_timeout=80
        volumes:
            - ./src:/app/src
            - ./tests:/app/tests
