app = "open-mt-api-staging"
primary_region = "cdg"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  release_command = "bash ./scripts/database.sh deploy"