version: "3.9"

services:
  open-mt-api:
    container_name: open-mt-api
    hostname: open-mt-api
    build:
      context: ..
    depends_on:
      - open-mt-database
    image: open-mt-api

  open-mt-database:
    container_name: open-mt-database
    hostname: open-mt-database
    image: postgres:15.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=open_mt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d