version: "3.9"
services:
    postgres:
        container_name: postgres
        image: postgres:13-alpine
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: myopenmarket
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./compose/postgres:/docker-entrypoint-initdb.d

    dev-api:
        container_name: dev-api
        depends_on:
            - postgres
        build: ..
        command: sh -c "yarn db:deploy-prod && yarn dev"
        environment:
            DATABASE_URL: postgresql://postgres:postgres@postgres:5432/myopenmarket?pool_timeout=80&connect_timeout=80
        volumes:
            - ../src:/app/src
            - ../tests:/app/tests
