name: CI Build Pipeline
on:
    pull_request:
        branches: [ develop, main ]
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: myopenmarket
                ports:
                    - 5432/tcp
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '16'
                cache: 'yarn'
            - run: yarn --ci
            - run: yarn test
