name: CI Build Pipeline
on:
    pull_request:
        branches: [ develop, main ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Test with the docker-compose stack
                run: yarn test:docker
